### ISSUE TITLE
running hubot-dotenv with an adapter

### ISSUE THREAD

**Issue by wickr-pak** [matzkoh/hubot-dotenv#1]
Hey Xluapp,

I can run this locally, but I am having trouble running this with an adapter. Any idea how can I run this with an adapter? 

Thanks in advance.

**Comment by liorbrauer** [comment]
Hi @wickr-pak,

Not an expert on this yet, but I'm trying to use `hubot-dotenv` with the `HipChat` adapter, and was successful with adding:
```json
"scripts": {
    "start": "hubot-dotenv -n simon-bot -a hipchat"
  }
```
to my `package.json` and then running `npm run start`
